#!/bin/bash

function get_full_path_name {
    local PARTIAL_PATH="$1"

    readlink -fn "$PARTIAL_PATH"
}

function get_existing_full_path_name {
    local PARTIAL_PATH="$1"
    local FULL_PATH=$(get_full_path_name "$PARTIAL_PATH")

    [ -e "$FULL_PATH" ] && echo "$FULL_PATH"
}

function get_current_script_path {
    local SOURCE="$1"

    echo $(get_existing_full_path_name "$SOURCE")
}

function get_vendor_name {
    local SOURCE="$1"
    local FULL_PATH=$(get_current_script_path "$SOURCE")
    local LIST=($(echo $FULL_PATH | tr "/" "\n"))
    local VENDOR_NAME=${LIST[-3]}

    echo ${VENDOR_NAME:-oxid-esales}
}

function print_variables_header {
    local NAME="$1"

    echo "Variables from: \"$(basename $NAME)\""
}
