#!/bin/bash

. $(dirname "$BASH_SOURCE")/oe-eshop-facts_helper

function main {
    get_input_values
    display_input_values
    export_input_values
    execute_script "$@"
}

function get_input_values {
    local SOURCE_PATH_SUFFIX="../../source/"
    local BOOTSTRAP_FN="bootstrap.php"
    local CONFIG_FN="config.inc.php"
    local VENDOR_SUFFIX="../vendor/"
    local VENDOR_BIN_SUFFIX="bin"

    : ${ESHOP_PHP_BIN_PATH:=$(which php)}
    : ${ESHOP_FACT_BIN_PATH:=$(get_current_script_path "$BASH_SOURCE")}
    : ${ESHOP_FACT_BASEDIR:=$(get_existing_full_path_name $(dirname "$BASH_SOURCE"))}
    : ${ESHOP_SOURCE_PATH:=$(get_existing_full_path_name "$ESHOP_FACT_BASEDIR/$SOURCE_PATH_SUFFIX")}
    : ${ESHOP_BOOTSTRAP_PATH:=$(get_existing_full_path_name "$ESHOP_SOURCE_PATH/$BOOTSTRAP_FN")}
    : ${ESHOP_CONFIG_PATH:=$(get_existing_full_path_name "$ESHOP_SOURCE_PATH/$CONFIG_FN")}
    : ${ESHOP_VENDOR_PATH:=$(get_existing_full_path_name "$ESHOP_SOURCE_PATH/$VENDOR_SUFFIX")}
    : ${ESHOP_VENDOR_BIN_PATH:=$(get_existing_full_path_name "$ESHOP_VENDOR_PATH/$VENDOR_BIN_SUFFIX")}
    : ${ESHOP_VENDOR_NAME:=$(get_vendor_name "$BASH_SOURCE")}
    : ${ESHOP_OXID_VENDOR_PATH:=$(get_existing_full_path_name "$ESHOP_VENDOR_PATH/$ESHOP_VENDOR_NAME")}
}

function display_input_values {
    [ "$ESHOP_VERBOSE_FACTS_DISPLAYED" == "1" ] && return 0

    if [ ! -z "$VERBOSE" ] || [ ! -z "$ESHOP_VERBOSE_FACTS" ] ; then
        print_variables_header "$BASH_SOURCE"
        echo -e "\tESHOP_PHP_BIN_PATH: $ESHOP_PHP_BIN_PATH"
        echo -e "\tESHOP_FACT_BIN_PATH: $ESHOP_FACT_BIN_PATH"
        echo -e "\tESHOP_FACT_BASEDIR: $ESHOP_FACT_BASEDIR"
        echo -e "\tESHOP_SOURCE_PATH: $ESHOP_SOURCE_PATH"
        echo -e "\tESHOP_BOOTSTRAP_PATH: $ESHOP_BOOTSTRAP_PATH"
        echo -e "\tESHOP_CONFIG_PATH: $ESHOP_CONFIG_PATH"
        echo -e "\tESHOP_VENDOR_PATH: $ESHOP_VENDOR_PATH"
        echo -e "\tESHOP_VENDOR_BIN_PATH: $ESHOP_VENDOR_BIN_PATH"
        echo -e "\tESHOP_VENDOR_NAME: $ESHOP_VENDOR_NAME"
        echo -e "\tESHOP_OXID_VENDOR_PATH: $ESHOP_OXID_VENDOR_PATH"
        echo ""

        ESHOP_VERBOSE_FACTS_DISPLAYED="1"
        export ESHOP_VERBOSE_FACTS_DISPLAYED="1"
    fi
}

function export_input_values {
    [ ! -z "$VERBOSE" ] && export VERBOSE="$VERBOSE"

    export ESHOP_FACTS=1
    export ESHOP_PHP_BIN_PATH="$ESHOP_PHP_BIN_PATH"
    export ESHOP_FACT_BIN_PATH="$ESHOP_FACT_BIN_PATH"
    export ESHOP_FACT_BASEDIR="$ESHOP_FACT_BASEDIR"
    export ESHOP_SOURCE_PATH="$ESHOP_SOURCE_PATH"
    export ESHOP_BOOTSTRAP_PATH="$ESHOP_BOOTSTRAP_PATH"
    export ESHOP_CONFIG_PATH="$ESHOP_CONFIG_PATH"
    export ESHOP_VENDOR_PATH="$ESHOP_VENDOR_PATH"
    export ESHOP_VENDOR_BIN_PATH="$ESHOP_VENDOR_BIN_PATH"
    export ESHOP_VENDOR_NAME="$ESHOP_VENDOR_NAME"
    export ESHOP_OXID_VENDOR_PATH="$ESHOP_OXID_VENDOR_PATH"
}

function execute_script {
    if [ ! -z "$1" ] ; then
        if [ -f "$ESHOP_VENDOR_BIN_PATH/$1" ] ; then
            "$ESHOP_VENDOR_BIN_PATH/$@"
        else
            echo -e "Script \"$1\" was not found. Possible candidates: \n"
            echo "$(ls -1 $ESHOP_VENDOR_BIN_PATH | grep oe- | grep -v $(basename $BASH_SOURCE))"
            exit 1
        fi
    fi
}

# http://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
[[ "${BASH_SOURCE[0]}" != "${0}" ]] || main $@
